server:
  port: 11000

spring:
  application:
    name: book-auth

  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/homework?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    ## 需要导入jdbc驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis
  session:
    store-type: redis

  redis:
    port: 6379
    host: 127.0.0.1
#    database: 5
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0 # 连接池中的最小空闲连接

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
